part 11
Bazih/mjs pull request #12
Opened 2022-08-02 19:26 UTC by Bazih

2022-08-03 07:58 UTC, fanisco requested changes

2022-08-03 07:58 UTC, fanisco commented on .gitignore
> +dist/
+ node_modules

2022-08-03 07:58 UTC, fanisco commented on src/chess/board.js
> +      ['wr', 'wkn', 'wb', 'wq', 'wk', 'wb', 'wkn', 'wr'],
Решили без констант в отдельном файле?

2022-08-03 07:58 UTC, fanisco commented on src/chess/bishop.js
> +export class Bishop extends Figure {
Принято именовать файл в том же стиле, что и класс/функция, экспортируемая из него. Здесь класс называется `Bishop` - значит и файл должен называться `Bishop.js`

2022-08-06 11:41 UTC, Bazih commented on .gitignore
> +dist/
Каталог уже добавлен

2022-08-06 19:36 UTC, fanisco approved these changes

2022-08-07 07:47 UTC, merged